NAMA: Muhammad Esza Maulana Firmanda

KELOMPOK: 10

1. Buatlah random array dengan nilai minimum 0 dan nilai maksimal 100 dan
jumlah baris 2 serta jumlah kolom 15

In [9]:
import numpy as np

array_random = np.random.randint(0, 101, size=(2, 15))

print(array_random)

[[28 30 44 45 82 42 45 37 17 40 21 26 95 56 83]
 [30 59 98 49 43 82 25  5 78 46  1 65  1 58  4]]


Hasil random nomor 1:
[[28 30 44 45 82 42 45 37 17 40 21 26 95 56 83],
 [30 59 98 49 43 82 25  5 78 46  1 65  1 58  4]]

2. Lakukan dot product pada array baris pertama tanpa index ke 0 & 1, dengan array baris kedua tanpa index ke 13 & 14

In [27]:
array_random = np.array(
 [[28, 30, 44, 45, 82, 42, 45, 37, 17, 40, 21, 26, 95, 56, 83],
  [30, 59, 98, 49, 43, 82, 25,  5, 78, 46, 1, 65, 1, 58, 4]])

# Mengambil subset elemen dari array pertama (indeks 0) tanpa index 0 & 1
subset_pertama = array_random[0, 2:]

# Mengambil subset elemen dari array kedua (indeks 1) tanpa index 13 & 14
subset_kedua = array_random[1, :13]

# Melakukan dot product pada kedua subset
dot_product = np.dot(subset_pertama, subset_kedua)

print("Hasil Dot Product:", dot_product)


Hasil Dot Product: 26315


3. Misalkan array baris pertama adalah nilai ujian matematika dan array baris kedua adalah nilai ujian biologi setiap siswa dengan nilai standar kelulusan adalah 79, buatlah function untuk menghitung rata-rata nilai matematika dari siswa yang tidak lolos pada ujian matematika ATAU biologi

MATEMATIKA

In [31]:
# Data nilai ujian matematika dan biologi
nilai_matematika = [28, 30, 44, 45, 82, 42, 45, 37, 17, 40, 21, 26, 95, 56, 83]
nilai_biologi = [30, 59, 98, 49, 43, 82, 25, 5, 78, 46, 1, 65, 1, 58, 4]

# Nilai standar kelulusan
KKM = 79

# Fungsi
def mean_matematika_tidak_lolos(nilai_matematika, nilai_biologi, KKM):
    tidak_lolos = (np.array(nilai_matematika) < KKM) | (np.array(nilai_biologi) < KKM)
    # Nilai matematika siswa yang tidak lolos
    nilai_matematika_tidak_lolos = np.array(nilai_matematika)[tidak_lolos]
    # Mean nilai matematika siswa yang tidak lolos
    rata_rata = np.mean(nilai_matematika_tidak_lolos)
    return rata_rata

# Panggil fungsi untuk menghitung rata-rata nilai matematika
hasil_mean = mean_matematika_tidak_lolos(nilai_matematika, nilai_biologi, KKM)
print("Rata-rata nilai matematika dari siswa yang tidak lolos:", hasil_mean)


Rata-rata nilai matematika dari siswa yang tidak lolos: 46.06666666666667


BIOLOGI

In [29]:
# Fungsi
def mean_biologi_tidak_lolos(nilai_matematika, nilai_biologi, KKM):
    tidak_lolos = (np.array(nilai_matematika) < KKM) | (np.array(nilai_biologi) < KKM)
    # Nilai Biologi siswa yang tidak lolos
    nilai_biologi_tidak_lolos = np.array(nilai_biologi)[tidak_lolos]
    # Mean nilai biologi siswa yang tidak lolos
    rata_rata = np.mean(nilai_biologi_tidak_lolos)
    return rata_rata

# Panggil fungsi untuk menghitung rata-rata nilai matematika
hasil_mean = mean_biologi_tidak_lolos(nilai_matematika, nilai_biologi, KKM)
print("Rata-rata nilai Biologi dari siswa yang tidak lolos:", hasil_mean)

Rata-rata nilai Biologi dari siswa yang tidak lolos: 42.93333333333333


4. Gunakan iteration untuk menghitung:

a. berapa siswa yang tidak lolos pada ujian matematika

In [24]:
# iterasi
jumlah_tidak_lolos = 0
for nilai in nilai_matematika:
    if nilai < KKM:
        jumlah_tidak_lolos += 1

print("Jumlah siswa yang tidak lolos ujian matematika", jumlah_tidak_lolos)

Jumlah siswa yang tidak lolos ujian matematika 12


b. berapa siswa yang tidak lolos pada ujian biologi

In [32]:
# iterasi
jumlah_tidak_lolos = 0
for nilai in nilai_biologi:
    if nilai < KKM:
        jumlah_tidak_lolos += 1

print("Jumlah siswa yang tidak lolos ujian biologi", jumlah_tidak_lolos)

Jumlah siswa yang tidak lolos ujian biologi 13
